export const mockData = [
  {
    id: 1,
    date: 'June 4, 2020',
    amount: '$4,321',
    type: 'Componsation & Pension Recurring',
    method: 'Direct Deposit',
    bank: 'USAA FEDERAL SAVINGS BANK',
    account: '1234567890999',
    rowClass: 'class',
  },
  {
    id: 2,
    date: 'June 3, 2020',
    amount: '$4,321',
    type: 'Componsation & Pension Recurring',
    method: 'Direct Deposit',
    bank: 'USAA FEDERAL SAVINGS BANK',
    account: '1234567890999',
    rowClass: 'class',
  },
  {
    id: 3,
    date: 'June 7, 2020',
    amount: '$$24',
    type: 'Some cool type',
    method: 'Mssenger pigeon',
    bank: 'Chase',
    account: '44',
    rowClass: 'class',
  },
  {
    id: 4,
    date: 'June 9, 2020',
    amount: '$672',
    type: 'Another cool type',
    method: 'Direct Deposit',
    bank: 'USAA FEDERAL SAVINGS BANK',
    account: '1234567890999',
    rowClass: 'class',
  },
  {
    id: 5,
    date: 'June 4, 2020',
    amount: '$4,321',
    type: 'Componsation & Pension Recurring',
    method: 'Direct Deposit',
    bank: 'USAA FEDERAL SAVINGS BANK',
    account: '1234567890999',
    rowClass: 'class',
  },
  {
    id: 6,
    date: 'June 3, 2020',
    amount: '$4,321',
    type: 'Componsation & Pension Recurring',
    method: 'Direct Deposit',
    bank: 'USAA FEDERAL SAVINGS BANK',
    account: '1234567890999',
    rowClass: 'class',
  },
  {
    id: 7,
    date: 'June 4, 2020',
    amount: '$4,321',
    type: 'Componsation & Pension Recurring',
    method: 'Direct Deposit',
    bank: 'USAA FEDERAL SAVINGS BANK',
    account: '1234567890999',
    rowClass: 'class',
  },
  {
    id: 8,
    date: 'June 3, 2020',
    amount: '$4,321',
    type: 'Componsation & Pension Recurring',
    method: 'Direct Deposit',
    bank: 'USAA FEDERAL SAVINGS BANK',
    account: '1234567890999',
    rowClass: 'class',
  },
  {
    id: 9,
    date: 'June 4, 2020',
    amount: '$4,321',
    type: 'Componsation & Pension Recurring',
    method: 'Direct Deposit',
    bank: 'USAA FEDERAL SAVINGS BANK',
    account: '1234567890999',
    rowClass: 'class',
  },
  {
    id: 10,
    date: 'June 3, 2020',
    amount: '$4,321',
    type: 'Componsation & Pension Recurring',
    method: 'Direct Deposit',
    bank: 'USAA FEDERAL SAVINGS BANK',
    account: '1234567890999',
    rowClass: 'class',
  },
  {
    id: 11,
    date: 'June 4, 2020',
    amount: '$4,321',
    type: 'Componsation & Pension Recurring',
    method: 'Direct Deposit',
    bank: 'USAA FEDERAL SAVINGS BANK',
    account: '1234567890999',
    rowClass: 'class',
  },
  {
    id: 12,
    date: 'June 3, 2020',
    amount: '$4,321',
    type: 'Componsation & Pension Recurring',
    method: 'Direct Deposit',
    bank: 'USAA FEDERAL SAVINGS BANK',
    account: '1234567890999',
    rowClass: 'class',
  },
];
